baseURL: "https://luigicennini.it/"
title: "luigi cennini"
theme: hugo-profile


outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

# Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

params:
  title: "Luigi Cennini"
  description: Luigi personal website
  # staticPath: ""  # The path to serve the static files from
  favicon: "https://avatars.githubusercontent.com/u/29329312?v=4"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    #defaultTheme: "dark" 

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    sections:
      - template: projects
        title: "projects"
        path: /projects
      - template: blog
        title: "blog"
        path: /blog

  sections:
    - template: projects
      title: "recent projects"
      path: projects
      maxShowNum: 4
    - template: handbooks
      title: "handbooks"
      path: handbooks
      maxShowNum: 3
    - template: blog
      title: "blog posts"
      path: blog   
      maxShowNum: 3
    
  contact:
    enable: false
    btnName: 
    email: luigi.cennini@libero.it
    

  # Hero
  hero:
    enable: true
    title: "Hi! I'm Luigi"
    content: "I am a graduate student in Computer Science & master Data Science student in Florence, Italy. In my spare time I like to write about my projects and I have put some of the best ones below. You will also find some post about stuff i find interesting."
    button:
      enable: false
      name: "CV"
      url: "https://drive.google.com/file/d/1ND4i3p8ysdkQPaZt5h0IZB4sSRsO_PM6/view?usp=sharing"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/giggiox
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/luigi-cennini-805991267
      

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
    
markup:
   tableOfContents:
      startLevel: 1
      endLevel: 6
