baseURL: ""
title: "luigi cennini"
theme: hugo-profile
defaultContentLanguage: it

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: progetti
      name: progetti
      title: progetti
      url: /projects
      weight: 1
    

params:
  title: "Luigi Cennini"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "https://avatars.githubusercontent.com/u/29329312?v=4"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    #brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    
    
  contact:
    enable: false
    # title: "Custom Name"
    btnName: 
    email: luigi.cennini@libero.it
    

  # Hero
  hero:
    enable: true
    intro: "Ciao! sono Luigi"
    title: "mi piace fare cose!"
    content: "Sono uno studente laureato in Informatica. Nel mio tempo libero mi piace scrivere dei miei progetti e ho messo qualcuno  dei migliori qui sotto."
    image: ""
    bottomImage:
      enable: false
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "CV"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/giggiox
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/luigi-cennini-805991267
          
    

  
  projects:
    recentPosts:
      path: "projects"
      count: 3
      title: progetti recenti
      enable: true
      disableFeaturedImage: false



  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: false
      content: "min read"
    scrollprogress:
      enable: true



  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
